# Non-interactive Arty S7-50 build: div_gen IP + RTL synth (+ optional impl/bitstream).
# Run from repo root via: vivado -mode batch -source scripts/vivado_build_arty_s7.tcl
# Quick synth only: set env VIVADO_SYNTH_ONLY=1 or pass --synth-only.
# Multi-date variant: set env VIVADO_MULTI_EXERCISE=1 or pass --multi-exercise.

set script_path [file normalize [info script]]
set script_dir [file dirname $script_path]
set repo_root [file normalize [file join $script_dir ..]]
source [file join $script_dir vivado_board_build_common.tcl]

cd $repo_root
puts "INFO: repo_root = $repo_root"

set synth_only 0
if {[info exists ::env(VIVADO_SYNTH_ONLY)] && ($::env(VIVADO_SYNTH_ONLY) eq "1")} {
    set synth_only 1
    puts "INFO: VIVADO_SYNTH_ONLY=1 - synthesis only (no place/route/bitstream)."
}
foreach arg $argv {
    if {$arg eq "--synth-only"} {
        set synth_only 1
        puts "INFO: --synth-only - synthesis only (no place/route/bitstream)."
    }
}

set multi_exercise 0
if {[info exists ::env(VIVADO_MULTI_EXERCISE)] && ($::env(VIVADO_MULTI_EXERCISE) eq "1")} {
    set multi_exercise 1
    puts "INFO: VIVADO_MULTI_EXERCISE=1 - building multi-exercise top variant."
}

set num_lanes 1
if {[info exists ::env(VIVADO_NUM_LANES)] && ($::env(VIVADO_NUM_LANES) ne "")} {
    set num_lanes $::env(VIVADO_NUM_LANES)
}
if {[lsearch -exact {1 2} $num_lanes] < 0} {
    puts "ERROR: Arty S7-50 board builds support NUM_LANES=1 or 2 (got $num_lanes)."
    exit 1
}
if {$multi_exercise} {
    puts "INFO: multi-date path/regression lanes = $num_lanes"
}
foreach arg $argv {
    if {$arg eq "--multi-exercise"} {
        set multi_exercise 1
        puts "INFO: --multi-exercise - building multi-exercise top variant."
    }
}

set clock_period_ns ""
if {[info exists ::env(VIVADO_CLOCK_PERIOD_NS)] && ($::env(VIVADO_CLOCK_PERIOD_NS) ne "")} {
    set clock_period_ns $::env(VIVADO_CLOCK_PERIOD_NS)
}
for {set i 0} {$i < [llength $argv]} {incr i} {
    if {[lindex $argv $i] eq "--clock-period-ns"} {
        incr i
        if {$i < [llength $argv]} {
            set clock_period_ns [lindex $argv $i]
        }
    }
}
if {$clock_period_ns eq ""} {
    set clock_period_ns 10.500
}
if {[catch {normalize_7series_core_clock $clock_period_ns} core_clock]} {
    puts "ERROR: $core_clock"
    exit 1
}
set core_clock_period_ns [dict get $core_clock period_ns]
set clock_literal [dict get $core_clock literal]
set core_freq_hz [dict get $core_clock frequency_hz]
set clock_tag [dict get $core_clock tag]
puts "INFO: S7 board input clock = 10.000 ns (100000000 Hz)"
puts "INFO: S7 generated core clock = $clock_literal ns ($core_freq_hz Hz)"

if {$multi_exercise} {
    set build_name "arty_s7_50_multi_lanes${num_lanes}_${clock_tag}ns"
} else {
    set build_name "arty_s7_50_single_lanes1_${clock_tag}ns"
}
set build_dir [file join $repo_root vivado_build $build_name]
if {[info exists ::env(VIVADO_BUILD_DIR)] && ($::env(VIVADO_BUILD_DIR) ne "")} {
    set build_dir [file normalize $::env(VIVADO_BUILD_DIR)]
    puts "INFO: S7 build directory override = $build_dir"
}

file mkdir $build_dir
foreach stale_name {arty_s7_qmc.bit arty_s7_qmc_multi.bit timing_post_route.rpt utilization.rpt drc_post_route.rpt route_status.rpt} {
    set stale_path [file join $build_dir $stale_name]
    if {[file exists $stale_path]} {
        file delete -force $stale_path
    }
}

set repo_slash [string map {\\ /} $repo_root]
set gen_dir [file join $build_dir generated]
file mkdir $gen_dir

# Keep the board oscillator constraint fixed at its physical 100 MHz rate.
# The wrapper's MMCM generic selects the generated core clock.
set xdc_source [file join $repo_root constraints arty_s7_50.xdc]
set gen_xdc [file join $gen_dir arty_s7_50_build.xdc]
file copy -force $xdc_source $gen_xdc
puts "INFO: copied fixed 100 MHz board constraint to $gen_xdc"
set gen_mem [file join $gen_dir mem_paths_pkg.sv]
set fh [open $gen_mem w]
puts $fh "// Auto-generated by vivado_build_arty_s7.tcl - do not edit"
puts $fh "package mem_paths_pkg;"
puts $fh "  parameter string REPO = \"$repo_slash\";"
puts $fh {  function automatic string join_path(input string rel);}
puts $fh {    if (REPO == "")}
puts $fh {      return rel;}
puts $fh {    return {REPO, "/", rel};}
puts $fh {  endfunction}
puts $fh {  parameter string DIRECTION_MEM = join_path("src/gen/direction.mem");}
puts $fh {  parameter string EXP_LUT      = join_path("src/gen/exp_lut_4096.mem");}
puts $fh {  parameter string EXP_SIGNED   = join_path("src/gen/exp_signed_lut_8192.mem");}
puts $fh {  parameter string LN_LUT       = join_path("src/gen/ln_lut_4096.mem");}
puts $fh {  parameter string SQRT_LUT     = join_path("src/gen/sqrt_lut_256.mem");}
puts $fh {endpackage}
close $fh
puts "INFO: wrote $gen_mem"

create_project -in_memory -part xc7s50csga324-1
set_property target_language Verilog [current_project]
set_property default_lib work [current_project]

# --- Divider IP (matches src/math/fxDiv.sv + Xilinx div_gen v5.1 veo) ---
set ip_dir [file join $build_dir generated_ip fxDiv_core]
if {[file exists $ip_dir]} {
    file delete -force $ip_dir
}
file mkdir $ip_dir
create_ip -name div_gen -vendor xilinx.com -library ip -version 5.1 -module_name fxDiv_core -dir $ip_dir
set ip [get_ips fxDiv_core]
set_property -dict [list \
    CONFIG.FlowControl {Blocking} \
    CONFIG.dividend_and_quotient_width {48} \
    CONFIG.divisor_width {32} \
    CONFIG.operand_sign {Signed} \
    CONFIG.remainder_type {Remainder} \
    CONFIG.algorithm_type {Radix2} \
    CONFIG.clocks_per_division {1} \
    CONFIG.latency_configuration {Manual} \
    CONFIG.latency {32} \
    CONFIG.OutTready {true} \
    CONFIG.ARESETN {true} \
] $ip
generate_target all [get_ips fxDiv_core]

# --- RTL ---
set rtl [list \
    $gen_mem \
    [file join $repo_root src fpga_cfg_pkg.sv] \
    [file join $repo_root src helpers rv_skid_arr_gate.sv] \
    [file join $repo_root src helpers event_align_fifo_arr.sv] \
    [file join $repo_root src math fxMul.sv] \
    [file join $repo_root src math fxDiv.sv] \
    [file join $repo_root src math fxExpLUT.sv] \
    [file join $repo_root src math fxLnLUT.sv] \
    [file join $repo_root src math fxSqrt.sv] \
    [file join $repo_root src math fxInvCDF_ZS.sv] \
    [file join $repo_root src steps sobol.sv] \
    [file join $repo_root src steps inverseCDF_fold.sv] \
    [file join $repo_root src steps inverseCDF.sv] \
    [file join $repo_root src steps GBM.sv] \
    [file join $repo_root src steps accumulator.sv] \
    [file join $repo_root src steps regression.sv] \
    [file join $repo_root src steps lsm_decision.sv] \
    [file join $repo_root src io uart uart_rx.sv] \
    [file join $repo_root src io uart uart_tx.sv] \
    [file join $repo_root src io uart uart_rx32.sv] \
    [file join $repo_root src io uart uart_tx32.sv] \
    [file join $repo_root src io handlers uart_input_handler.sv] \
    [file join $repo_root src top top_option_pricer_multi.sv] \
    [file join $repo_root src top top_option_pricer_multi_stored.sv] \
    [file join $repo_root src top top_option_pricer.sv] \
    [file join $repo_root fpga arty_s7_option_pricer_top.sv] \
]
foreach f $rtl {
    if {![file exists $f]} {
        puts "ERROR: missing source $f"
        exit 1
    }
}
add_files -fileset sources_1 -norecurse $rtl

set mem_files [glob -nocomplain [file join $repo_root src gen *.mem]]
foreach m $mem_files {
    add_files -fileset sources_1 -norecurse $m
}

add_files -fileset constrs_1 -norecurse $gen_xdc

set_property top arty_s7_option_pricer_top [get_filesets sources_1]
if {[info exists ::env(VIVADO_UART_DIAGNOSTIC)] && ($::env(VIVADO_UART_DIAGNOSTIC) eq "1")} {
    set_property verilog_define {UART_PHYSICAL_DIAGNOSTIC} [get_filesets sources_1]
    puts "INFO: UART_PHYSICAL_DIAGNOSTIC enabled."
}
set top_generics [list CORE_CLKOUT_DIVIDE_F=$clock_literal CORE_CLK_FREQ_HZ=$core_freq_hz]
if {$multi_exercise} {
    lappend top_generics MULTI_EXERCISE=1 NUM_LANES=$num_lanes
    lappend top_generics MULTI_CORE_MAX_CYCLES=1000000000
}
set_property generic $top_generics [get_filesets sources_1]
puts "INFO: top generics = $top_generics"
update_compile_order -fileset sources_1

puts "INFO: Running in-process synth_design."
puts "INFO: Synthesizing divider IP in-process for direct synth_design."
synth_ip [get_ips fxDiv_core]
if {$multi_exercise} {
    if {$num_lanes > 1} {
        # The two-lane stored-path core is close to the S7-50 LUT ceiling.
        # Ask synthesis to compact area before declaring that configuration
        # infeasible; functional arithmetic and pipeline latency are unchanged.
        synth_design -top arty_s7_option_pricer_top -part xc7s50csga324-1 \
            -generic $top_generics -directive AreaOptimized_high
    } else {
        synth_design -top arty_s7_option_pricer_top -part xc7s50csga324-1 -generic $top_generics
    }
} else {
    synth_design -top arty_s7_option_pricer_top -part xc7s50csga324-1 -generic $top_generics
}
write_checkpoint -force [file join $build_dir synth.dcp]
report_utilization -file [file join $build_dir utilization_synth.rpt]

set gui_project [create_verified_post_synth_project \
    $build_dir arty_s7_qmc_post_synth xc7s50csga324-1 \
    arty_s7_option_pricer_top $gen_xdc ExploreArea]
puts "INFO: Canonical GUI implementation project: $gui_project"

if {$synth_only} {
    puts "INFO: Synth-only mode - wrote [file join $build_dir synth.dcp]"
    puts "INFO: Synth-only mode - wrote [file join $build_dir utilization_synth.rpt]"
    exit 0
}

if {$multi_exercise} {
    set mode multi
    set bit_name arty_s7_qmc_multi.bit
} else {
    set mode single
    set bit_name arty_s7_qmc.bit
}
set implementation_result [run_verified_post_synth_implementation \
    $build_dir arty_s7_option_pricer_top $bit_name ExploreArea]
write_board_build_manifest \
    $build_dir arty_s7_50 xc7s50csga324-1 arty_s7_option_pricer_top \
    $mode $num_lanes $core_clock_period_ns $core_freq_hz $implementation_result
puts "INFO: Build completed with verified timing and bitstream."
exit 0
