# Non-interactive Arty S7-50 build: div_gen IP + RTL synth (+ optional impl/bitstream).
# Run from repo root via: vivado -mode batch -source scripts/vivado_build_arty_s7.tcl
# Quick synth only: set env VIVADO_SYNTH_ONLY=1 or pass --synth-only.
# Multi-date variant: set env VIVADO_MULTI_EXERCISE=1 or pass --multi-exercise.

set script_path [file normalize [info script]]
set script_dir [file dirname $script_path]
set repo_root [file normalize [file join $script_dir ..]]

cd $repo_root
puts "INFO: repo_root = $repo_root"

set synth_only 0
if {[info exists ::env(VIVADO_SYNTH_ONLY)] && ($::env(VIVADO_SYNTH_ONLY) eq "1")} {
    set synth_only 1
    puts "INFO: VIVADO_SYNTH_ONLY=1 - synthesis only (no place/route/bitstream)."
}
foreach arg $argv {
    if {$arg eq "--synth-only"} {
        set synth_only 1
        puts "INFO: --synth-only - synthesis only (no place/route/bitstream)."
    }
}

set multi_exercise 0
if {[info exists ::env(VIVADO_MULTI_EXERCISE)] && ($::env(VIVADO_MULTI_EXERCISE) eq "1")} {
    set multi_exercise 1
    puts "INFO: VIVADO_MULTI_EXERCISE=1 - building multi-exercise top variant."
}
foreach arg $argv {
    if {$arg eq "--multi-exercise"} {
        set multi_exercise 1
        puts "INFO: --multi-exercise - building multi-exercise top variant."
    }
}

set clock_period_ns ""
if {[info exists ::env(VIVADO_CLOCK_PERIOD_NS)] && ($::env(VIVADO_CLOCK_PERIOD_NS) ne "")} {
    set clock_period_ns $::env(VIVADO_CLOCK_PERIOD_NS)
}
for {set i 0} {$i < [llength $argv]} {incr i} {
    if {[lindex $argv $i] eq "--clock-period-ns"} {
        incr i
        if {$i < [llength $argv]} {
            set clock_period_ns [lindex $argv $i]
        }
    }
}
if {$clock_period_ns ne ""} {
    set ::S7_SYS_CLK_PERIOD_NS $clock_period_ns
    puts "INFO: S7 sys_clk period override = $::S7_SYS_CLK_PERIOD_NS ns"
}

if {$multi_exercise} {
    set build_dir [file join $repo_root vivado_build arty_s7_50_multi]
} else {
    set build_dir [file join $repo_root vivado_build arty_s7_50]
}
if {$clock_period_ns ne ""} {
    set clock_tag [string map {. p} $clock_period_ns]
    set build_dir "${build_dir}_${clock_tag}ns"
}
file mkdir $build_dir

set repo_slash [string map {\\ /} $repo_root]
set gen_dir [file join $build_dir generated]
file mkdir $gen_dir
set gen_mem [file join $gen_dir mem_paths_pkg.sv]
set fh [open $gen_mem w]
puts $fh "// Auto-generated by vivado_build_arty_s7.tcl - do not edit"
puts $fh "package mem_paths_pkg;"
puts $fh "  parameter string REPO = \"$repo_slash\";"
puts $fh {  function automatic string join_path(input string rel);}
puts $fh {    if (REPO == "")}
puts $fh {      return rel;}
puts $fh {    return {REPO, "/", rel};}
puts $fh {  endfunction}
puts $fh {  parameter string DIRECTION_MEM = join_path("src/gen/direction.mem");}
puts $fh {  parameter string EXP_LUT      = join_path("src/gen/exp_lut_4096.mem");}
puts $fh {  parameter string EXP_SIGNED   = join_path("src/gen/exp_signed_lut_8192.mem");}
puts $fh {  parameter string LN_LUT       = join_path("src/gen/ln_lut_4096.mem");}
puts $fh {  parameter string SQRT_LUT     = join_path("src/gen/sqrt_lut_256.mem");}
puts $fh {endpackage}
close $fh
puts "INFO: wrote $gen_mem"

create_project -force arty_s7_qmc $build_dir -part xc7s50csga324-1
set_property target_language Verilog [current_project]
set_property default_lib work [current_project]

# --- Divider IP (matches src/math/fxDiv.sv + Xilinx div_gen v5.1 veo) ---
set ip_dir [file join $build_dir generated_ip fxDiv_core]
file mkdir $ip_dir
create_ip -name div_gen -vendor xilinx.com -library ip -version 5.1 -module_name fxDiv_core -dir $ip_dir
set ip [get_ips fxDiv_core]
set_property -dict [list \
    CONFIG.FlowControl {Blocking} \
    CONFIG.dividend_and_quotient_width {48} \
    CONFIG.divisor_width {32} \
    CONFIG.operand_sign {Signed} \
    CONFIG.remainder_type {Remainder} \
    CONFIG.algorithm_type {Radix2} \
    CONFIG.clocks_per_division {1} \
    CONFIG.latency_configuration {Manual} \
    CONFIG.latency {32} \
    CONFIG.OutTready {true} \
    CONFIG.ARESETN {true} \
] $ip
generate_target all [get_ips fxDiv_core]

# --- RTL ---
set rtl [list \
    $gen_mem \
    [file join $repo_root src fpga_cfg_pkg.sv] \
    [file join $repo_root src helpers rv_skid_arr_gate.sv] \
    [file join $repo_root src helpers event_align_fifo_arr.sv] \
    [file join $repo_root src math fxMul.sv] \
    [file join $repo_root src math fxDiv.sv] \
    [file join $repo_root src math fxExpLUT.sv] \
    [file join $repo_root src math fxLnLUT.sv] \
    [file join $repo_root src math fxSqrt.sv] \
    [file join $repo_root src math fxInvCDF_ZS.sv] \
    [file join $repo_root src steps sobol.sv] \
    [file join $repo_root src steps inverseCDF_fold.sv] \
    [file join $repo_root src steps inverseCDF.sv] \
    [file join $repo_root src steps GBM.sv] \
    [file join $repo_root src steps accumulator.sv] \
    [file join $repo_root src steps regression.sv] \
    [file join $repo_root src steps lsm_decision.sv] \
    [file join $repo_root src io uart uart_rx.sv] \
    [file join $repo_root src io uart uart_tx.sv] \
    [file join $repo_root src io uart uart_rx32.sv] \
    [file join $repo_root src io uart uart_tx32.sv] \
    [file join $repo_root src io handlers uart_input_handler.sv] \
    [file join $repo_root src top top_option_pricer_multi.sv] \
    [file join $repo_root src top top_option_pricer.sv] \
    [file join $repo_root fpga arty_s7_option_pricer_top.sv] \
]
foreach f $rtl {
    if {![file exists $f]} {
        puts "ERROR: missing source $f"
        exit 1
    }
}
add_files -fileset sources_1 -norecurse $rtl

set mem_files [glob -nocomplain [file join $repo_root src gen *.mem]]
foreach m $mem_files {
    add_files -fileset sources_1 -norecurse $m
}

add_files -fileset constrs_1 -norecurse [file join $repo_root constraints arty_s7_50.xdc]

set_property top arty_s7_option_pricer_top [get_filesets sources_1]
if {$multi_exercise} {
    set top_generics {MULTI_EXERCISE=1 MULTI_CORE_MAX_CYCLES=1000000000}
    set_property generic $top_generics [get_filesets sources_1]
    puts "INFO: top generics = $top_generics"
}
update_compile_order -fileset sources_1

puts "INFO: Running in-process synth_design."
puts "INFO: Synthesizing divider IP in-process for direct synth_design."
synth_ip [get_ips fxDiv_core]
if {$multi_exercise} {
    synth_design -top arty_s7_option_pricer_top -part xc7s50csga324-1 -generic {MULTI_EXERCISE=1 MULTI_CORE_MAX_CYCLES=1000000000}
} else {
    synth_design -top arty_s7_option_pricer_top -part xc7s50csga324-1
}
write_checkpoint -force [file join $build_dir synth.dcp]
report_utilization -file [file join $build_dir utilization_synth.rpt]

if {$synth_only} {
    puts "INFO: Synth-only mode - wrote [file join $build_dir synth.dcp]"
    puts "INFO: Synth-only mode - wrote [file join $build_dir utilization_synth.rpt]"
    exit 0
}

puts "INFO: Running in-process implementation."
opt_design
write_checkpoint -force [file join $build_dir opt.dcp]

place_design
write_checkpoint -force [file join $build_dir place.dcp]
phys_opt_design -directive Explore
write_checkpoint -force [file join $build_dir place_phys_opt.dcp]

route_design
write_checkpoint -force [file join $build_dir route.dcp]

report_route_status -file [file join $build_dir route_status.rpt]
report_timing_summary -file [file join $build_dir timing_post_route.rpt] -max_paths 20
report_utilization -file [file join $build_dir utilization.rpt]
report_drc -file [file join $build_dir drc_post_route.rpt]

if {$multi_exercise} {
    set bit_dst [file join $build_dir arty_s7_qmc_multi.bit]
} else {
    set bit_dst [file join $build_dir arty_s7_qmc.bit]
}
write_bitstream -force $bit_dst
puts "INFO: Bitstream: $bit_dst"
exit 0
